### ISSUE TITLE
class-based views

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-DrEdi#11]
TBA

**Comment by webknjaz** [comment]
@DrEdi please write comprehensive description of this task and remove `[DRAFT] ` mark after that :)

**Comment by DrEdi** [comment]
1. Read about class-based views in docs
- [ ] intro https://docs.djangoproject.com/en/1.10/topics/class-based-views/intro/
- [ ] advanced https://docs.djangoproject.com/en/1.10/topics/class-based-views/
2. Rewrite yours

p.s - don't forget that tests MUST be done before you start this task

**Comment by webknjaz** [comment]
Please spread this across repos once you complete the description and then you may close this ticket.

**Comment by DrEdi** [comment]
One question: is it enough? I do not know what i could put there more :)

**Comment by webknjaz** [comment]
I guess so, you'll notice if some questions appear ;)
