### ISSUE TITLE
Configure integration of Heroku deployment with GitHub

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-DrEdi#18]
* [x] Accept invitation to [this organization](https://github.com/kpi-web-guild)
 * optionally make your membership public, so that there will be hat logo displayed on your profile page ^^
* [x] Choose [this repo](https://github.com/kpi-web-guild/django-girls-blog-DrEdi) in `Heroku Dashboard` on `Deploy` page
* [x] Make [`master` branch](https://github.com/kpi-web-guild/django-girls-blog-DrEdi/tree/master) be deployed on update once the tests pass

**Comment by DrEdi** [comment]
https://myownsuperblog.herokuapp.com/

Here we are :)
